name: Update docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checks 
        uses: action/checkout@v3
        id: docker-hub
        env:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build image
        id: build-docker-image
        run: docker build . -f Dockerfile -t ivan12345abc/legalario_hub:v1.0
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKER_USERNAME}}//legalario_hub:v1.0
      
     
    
