name: Update docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checks 
        uses: action/checkout@v4
      - name: build image
        run: docker build . -t ivan12345abc/legalario_hub:v1.0
      - name: publish_images
        run:
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          docker push ivan12345abc/legalario_hub:v1.0
