name: Build and Push Docker image EC2

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: DockerFileFolder/
          push: true
          tags: ivan12345abc/legalario_hub:v1.0
     
      - name: Install SSH Key 
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Deploy Docker image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER}}@${{ secrets.EC2_INSTANCE_IP}} << 'EOF'
          docker pull ivan12345abc/legalario_hub:v1.0
          
          docker container run -d -p 8080:80 --name legalario_container legalario_hub:v1.0
          EOF